"""
Django settings for config project.

Environment variables are loaded from a `.env` file at the project root (if present),
generated by `dev_tools/generate_env.py`. See that script for variable documentation.
"""

from pathlib import Path
import os
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    if not path.is_file():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if not key or key in os.environ:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / ".env")


def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: list[str]) -> list[str]:
    raw = os.environ.get(name)
    if raw is None or not raw.strip():
        return default
    return [p.strip() for p in raw.split(",") if p.strip()]


def _database_from_url(url: str) -> dict:
    parsed = urlparse(url)
    scheme = (parsed.scheme or "").lower()

    if scheme in ("sqlite", "sqlite3"):
        # sqlite:///relative.db  -> path "/relative.db" (relative to BASE_DIR)
        # sqlite:////tmp/abs.db -> path "//tmp/abs.db" (absolute on Unix)
        path = unquote(parsed.path or "")
        if not path:
            name = BASE_DIR / "db.sqlite3"
        elif path.startswith("//"):
            # Leading slash pair: fourth slash in URL starts absolute path.
            name = path[1:]
        elif path.startswith("/"):
            rel = path.lstrip("/")
            name = BASE_DIR / rel
        else:
            name = BASE_DIR / "db.sqlite3"
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(name),
        }

    if scheme in ("postgres", "postgresql"):
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (parsed.path or "").lstrip("/"),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or ""),
        }

    raise ValueError(f"Unsupported DATABASE_URL scheme: {scheme!r}")


# -----------------------------------------------------------------------------
# Core
# -----------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-x9!dk4fgyuqgf8nktzq=+ni1zw_&r^hvwcfn)_5h&hxj-x=@3d",
)

DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", [])


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mozilla_django_oidc",
    "app.public_app",
    "app.administration",
    "app.events",
    "app.assets",
    "app.detail_extensions",
    "app.parts",
    "app.procurement",
    "app.inventory",
    "app.maintenance",
    "app.dispatching",
]

AUTH_USER_MODEL = "administration.User"

LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "app.administration.auth_backends.MicrosoftOIDCBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_database_url = os.environ.get("DATABASE_URL", "").strip()
if _database_url:
    DATABASES = {"default": _database_from_url(_database_url)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation — OWASP-compliant
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html
#
# OWASP guidance:
# - Minimum length requirement (12 chars) without complexity/mixture rules
# - Check against common/breached passwords
# - Check against user attributes (username, email, etc.)
# - No expiration, no history, no forced periodic changes
# - Allow spaces and special characters

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "app.administration.control_layer.password_validators.OWASPMinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

if (BASE_DIR / "static").is_dir():
    STATICFILES_DIRS = [BASE_DIR / "static"]
else:
    STATICFILES_DIRS = []

_static_root = os.environ.get("STATIC_ROOT", "").strip()
STATIC_ROOT = _static_root or None

_media_root = os.environ.get("MEDIA_ROOT", "").strip()
MEDIA_ROOT = Path(_media_root) if _media_root else BASE_DIR / "media"
MEDIA_URL = os.environ.get("MEDIA_URL", "media/")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# -----------------------------------------------------------------------------
# Django admin UI (django-jazzmin)
# https://django-jazzmin.readthedocs.io/
# -----------------------------------------------------------------------------

JAZZMIN_SETTINGS = {
    "site_title": "Asset Management",
    "site_header": "Asset Management",
    "site_brand": "Asset Management",
    "welcome_sign": "Sign in to continue",
    "copyright": "",
    "show_ui_builder": False,
}


# -----------------------------------------------------------------------------
# Security (HTTPS / reverse proxy)
# -----------------------------------------------------------------------------

SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False)

SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", False)

CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", False)

CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS", [])

USE_X_FORWARDED_HOST = _env_bool("USE_X_FORWARDED_HOST", False)

_proxy_header = os.environ.get("SECURE_PROXY_SSL_HEADER", "").strip()
if _proxy_header and "," in _proxy_header:
    h_name, h_val = _proxy_header.split(",", 1)
    SECURE_PROXY_SSL_HEADER = (h_name.strip(), h_val.strip())
else:
    SECURE_PROXY_SSL_HEADER = None


# -----------------------------------------------------------------------------
# OIDC (Microsoft Entra ID / Azure AD)
# https://mozilla-django-oidc.readthedocs.io/
# -----------------------------------------------------------------------------

OIDC_RP_CLIENT_ID = os.environ.get("OIDC_RP_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = os.environ.get("OIDC_RP_CLIENT_SECRET", "")
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_SCOPES = "openid email profile"

OIDC_OP_AUTHORIZATION_ENDPOINT = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize"
OIDC_OP_TOKEN_ENDPOINT = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
OIDC_OP_USER_ENDPOINT = "https://graph.microsoft.com/oidc/userinfo"
OIDC_OP_JWKS_ENDPOINT = "https://login.microsoftonline.com/common/discovery/v2.0/keys"

OIDC_CREATE_USER = True
OIDC_STORE_ACCESS_TOKEN = False
OIDC_AUTHENTICATION_CALLBACK_URL = "oidc_authentication_callback"


# -----------------------------------------------------------------------------
# Hashids (URL-safe PK encoding)
# -----------------------------------------------------------------------------

HASHIDS_SALT = os.environ.get("HASHIDS_SALT", "dev-insecure-hashids-salt-do-not-use-in-production")
