# Generated by Django 6.0.5 on 2026-07-12 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('part_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_domain_limited', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documents_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_documents_thread', to='events.activitythread')),
                ('gallery_thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_gallery_thread', to='events.activitythread')),
                ('primary_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_of_part', to='events.attachment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'part',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='PartManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'part_manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer_part_number', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_major_revision_number', models.PositiveIntegerField(blank=True, null=True)),
                ('min_minor_revision_number', models.PositiveIntegerField(blank=True, null=True)),
                ('max_major_revision_number', models.PositiveIntegerField(blank=True, null=True)),
                ('max_minor_revision_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('internal_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='parts.part')),
                ('part_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='parts.partmanufacturer')),
                ('thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_item_thread', to='events.activitythread')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_item',
                'ordering': ['part_manufacturer', 'manufacturer_part_number'],
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(db_index=True, max_length=200)),
                ('normalized_value', models.CharField(db_index=True, max_length=200)),
                ('alias_type', models.CharField(max_length=50)),
                ('association_type', models.CharField(choices=[('part_to_vendor_item', 'Part to Vendor Item'), ('part_to_part', 'Part to Part'), ('part_to_string', 'Part to String')], max_length=30)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('alternate_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_aliases', to='parts.part')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='parts.part')),
                ('supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='parts.supplieritem')),
            ],
            options={
                'db_table': 'part_alias',
                'ordering': ['normalized_value'],
            },
        ),
        migrations.CreateModel(
            name='PartDomainAccessMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_domain_access_mappings', to='administration.domain')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_access_mappings', to='parts.part')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'part_domain_access_mapping',
                'constraints': [models.UniqueConstraint(fields=('part', 'domain'), name='uniq_part_domain_access_mapping')],
            },
        ),
        migrations.CreateModel(
            name='PartRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('date_of_release', models.DateField(blank=True, null=True)),
                ('major_revision_number', models.PositiveIntegerField()),
                ('minor_revision_number', models.PositiveIntegerField(default=0)),
                ('major_revision_name', models.CharField(blank=True, max_length=100, null=True)),
                ('minor_revision_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('redline', 'Redline'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='parts.part')),
                ('thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_revision_thread', to='events.activitythread')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'part_revision',
                'ordering': ['part', '-major_revision_number', '-minor_revision_number'],
                'constraints': [models.UniqueConstraint(fields=('part', 'major_revision_number', 'minor_revision_number'), name='uniq_part_revision_major_minor'), models.UniqueConstraint(fields=('part', 'sequence'), name='uniq_part_revision_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('part_manufacturer', 'manufacturer_part_number'), name='uniq_supplier_item_mfr_mpn'),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.UniqueConstraint(fields=('alias_type', 'normalized_value'), name='uniq_alias_type_normalized_value'),
        ),
        migrations.AddConstraint(
            model_name='alias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alternate_part__isnull', True), ('association_type', 'part_to_vendor_item'), ('supplier_item__isnull', False)), models.Q(('alternate_part__isnull', False), ('association_type', 'part_to_part'), ('supplier_item__isnull', True)), models.Q(('alternate_part__isnull', True), ('association_type', 'part_to_string'), ('supplier_item__isnull', True)), _connector='OR'), name='alias_association_type_secondary_fk_consistency'),
        ),
    ]
