# Generated by Django 6.0.5 on 2026-06-10 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restrict_to_domain_set', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_class',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('capability_status', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('depth_from_root', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meter1', models.FloatField(blank=True, null=True)),
                ('meter2', models.FloatField(blank=True, null=True)),
                ('meter3', models.FloatField(blank=True, null=True)),
                ('meter4', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documentation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_asset', to='events.activitythread')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='administration.domain')),
                ('parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset')),
                ('photo_gallery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='photo_gallery_asset', to='events.fileset')),
                ('root_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='assets.asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetclass')),
            ],
            options={
                'db_table': 'asset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetClassDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='assets.assetclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_links', to='administration.domain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_class_domain',
            },
        ),
        migrations.AddField(
            model_name='assetclass',
            name='domains',
            field=models.ManyToManyField(related_name='asset_classes', through='assets.AssetClassDomain', to='administration.domain'),
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_events', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_event',
            },
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_image_links', to='events.file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_image',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=200)),
                ('subtype_name', models.CharField(blank=True, max_length=200, null=True)),
                ('revision', models.CharField(blank=True, max_length=100, null=True)),
                ('is_base_model', models.BooleanField(default=True)),
                ('meter1_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('meter2_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('meter3_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('meter4_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='assets.assetclass')),
                ('base_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assets.assetmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_model',
                'ordering': ['model_name', 'subtype_name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetmodel'),
        ),
        migrations.CreateModel(
            name='AssetParentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_history', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('new_parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('new_root_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('previous_parent_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('previous_root_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_parent_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capability_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetClassCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='assets.assetclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('capability_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_links', to='assets.capabilitydefinition')),
            ],
            options={
                'db_table': 'asset_class_capability',
            },
        ),
        migrations.CreateModel(
            name='AssetCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('capability_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='assets.capabilitydefinition')),
            ],
            options={
                'db_table': 'asset_capability',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('revision', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_templates', to='assets.assetmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuration_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documented_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('partial', 'Partial'), ('complete', 'Complete')], default='unverified', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_configurations', to='assets.configurationtemplate')),
            ],
            options={
                'db_table': 'asset_configuration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefinedModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicability_mode', models.CharField(choices=[('strict', 'Class and model'), ('class_only', 'Class only'), ('model_set', 'Model set'), ('unrestricted', 'Unrestricted')], default='unrestricted', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'defined_modification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActualModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_creation_records', to='events.event')),
                ('removal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_removal_records', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_modifications', to='assets.asset')),
                ('defined_modification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_applications', to='assets.definedmodification')),
            ],
            options={
                'db_table': 'actual_modification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_index', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_history', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meter_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capability_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='assets.capabilitydefinition')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='assets.assetmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_model_capability',
            },
        ),
        migrations.CreateModel(
            name='ModelDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_links', to='administration.domain')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='assets.assetmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_model_domain',
            },
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='domains',
            field=models.ManyToManyField(related_name='asset_models', through='assets.ModelDomain', to='administration.domain'),
        ),
        migrations.CreateModel(
            name='ModelManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='assets.manufacturer')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='assets.assetmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_model_manufacturer',
            },
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='manufacturers',
            field=models.ManyToManyField(related_name='models', through='assets.ModelManufacturer', to='assets.manufacturer'),
        ),
        migrations.CreateModel(
            name='ModificationAssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allowlist', to='assets.definedmodification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modification_asset_class',
            },
        ),
        migrations.CreateModel(
            name='ModificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_allowlist', to='assets.definedmodification')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'modification_model',
            },
        ),
        migrations.CreateModel(
            name='TemplateChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('child_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_child_declarations', to='assets.assetmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_declarations', to='assets.configurationtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_child',
            },
        ),
        migrations.CreateModel(
            name='TemplateModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_notes', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('defined_modification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_links', to='assets.definedmodification')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_links', to='assets.configurationtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_modification',
            },
        ),
        migrations.AddConstraint(
            model_name='assetclassdomain',
            constraint=models.UniqueConstraint(fields=('asset_class', 'domain'), name='uq_asset_class_domain'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['asset'], name='asset_event_asset_i_499273_idx'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['event'], name='asset_event_event_i_e2e04e_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetevent',
            constraint=models.UniqueConstraint(fields=('asset', 'event'), name='uq_asset_event'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['domain'], name='asset_domain__24a786_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_class'], name='asset_asset_c_92c528_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['model'], name='asset_model_i_8c5b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['parent_asset'], name='asset_parent__a26e30_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['root_asset'], name='asset_root_as_22dc46_idx'),
        ),
        migrations.AddIndex(
            model_name='assetparenthistory',
            index=models.Index(fields=['asset', '-created_at'], name='asset_paren_asset_i_2d2f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetclasscapability',
            constraint=models.UniqueConstraint(fields=('asset_class', 'capability_definition'), name='uq_asset_class_capability'),
        ),
        migrations.AddConstraint(
            model_name='assetcapability',
            constraint=models.UniqueConstraint(fields=('asset', 'capability_definition'), name='uq_asset_capability'),
        ),
        migrations.AddIndex(
            model_name='meterhistory',
            index=models.Index(fields=['asset', 'meter_index'], name='meter_histo_asset_i_713a38_idx'),
        ),
        migrations.AddIndex(
            model_name='meterhistory',
            index=models.Index(fields=['recorded_at'], name='meter_histo_recorde_1bec8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelcapability',
            constraint=models.UniqueConstraint(fields=('model', 'capability_definition'), name='uq_asset_model_capability'),
        ),
        migrations.AddConstraint(
            model_name='modeldomain',
            constraint=models.UniqueConstraint(fields=('model', 'domain'), name='uq_asset_model_domain'),
        ),
        migrations.AddConstraint(
            model_name='modelmanufacturer',
            constraint=models.UniqueConstraint(fields=('model', 'manufacturer'), name='uq_asset_model_manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='modificationassetclass',
            constraint=models.UniqueConstraint(fields=('defined_modification', 'asset_class'), name='uq_modification_asset_class'),
        ),
        migrations.AddConstraint(
            model_name='modificationmodel',
            constraint=models.UniqueConstraint(fields=('defined_modification', 'model'), name='uq_modification_model'),
        ),
        migrations.AddConstraint(
            model_name='templatemodification',
            constraint=models.UniqueConstraint(fields=('template', 'defined_modification'), name='uq_template_modification'),
        ),
    ]
