# Generated by Django 6.0.7 on 2026-08-21 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('assets', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actualmodification',
            name='creation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_creation_records', to='events.event'),
        ),
        migrations.AddField(
            model_name='actualmodification',
            name='removal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_removal_records', to='events.event'),
        ),
        migrations.AddField(
            model_name='actualmodification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='documentation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_asset', to='events.activitythread'),
        ),
        migrations.AddField(
            model_name='asset',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='administration.domain'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='photo_gallery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='photo_gallery_asset', to='events.fileset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_of_asset', to='events.attachment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='root_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualmodification',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_modifications', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetcapability',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetcapability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcapability',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetclass'),
        ),
        migrations.AddField(
            model_name='assetclasscapability',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='assets.assetclass'),
        ),
        migrations.AddField(
            model_name='assetclasscapability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclasscapability',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclassdomain',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='assets.assetclass'),
        ),
        migrations.AddField(
            model_name='assetclassdomain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclassdomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_links', to='administration.domain'),
        ),
        migrations.AddField(
            model_name='assetclassdomain',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclass',
            name='domains',
            field=models.ManyToManyField(related_name='asset_classes', through='assets.AssetClassDomain', to='administration.domain'),
        ),
        migrations.AddField(
            model_name='assetconfiguration',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='assets.assetclass'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='base_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='documentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_documentation', to='events.activitythread'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='photo_gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_photo_gallery', to='events.fileset'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_of_asset_model', to='events.attachment'),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_history', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='new_parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='new_root_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='previous_parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='previous_root_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetparenthistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capabilitydefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capabilitydefinition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetclasscapability',
            name='capability_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_class_links', to='assets.capabilitydefinition'),
        ),
        migrations.AddField(
            model_name='assetcapability',
            name='capability_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='assets.capabilitydefinition'),
        ),
        migrations.AddField(
            model_name='configurationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationtemplate',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_templates', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='configurationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetconfiguration',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_configurations', to='assets.configurationtemplate'),
        ),
        migrations.AddField(
            model_name='definedmodification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='definedmodification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualmodification',
            name='defined_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_applications', to='assets.definedmodification'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterhistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_history', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='meterhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelcapability',
            name='capability_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='assets.capabilitydefinition'),
        ),
        migrations.AddField(
            model_name='modelcapability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelcapability',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='modelcapability',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeldomain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeldomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_model_links', to='administration.domain'),
        ),
        migrations.AddField(
            model_name='modeldomain',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='modeldomain',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='domains',
            field=models.ManyToManyField(related_name='asset_models', through='assets.ModelDomain', to='administration.domain'),
        ),
        migrations.AddField(
            model_name='modelmanufacturer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelmanufacturer',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_links', to='assets.manufacturer'),
        ),
        migrations.AddField(
            model_name='modelmanufacturer',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='modelmanufacturer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='manufacturers',
            field=models.ManyToManyField(related_name='models', through='assets.ModelManufacturer', to='assets.manufacturer'),
        ),
        migrations.AddField(
            model_name='modificationassetclass',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetclass'),
        ),
        migrations.AddField(
            model_name='modificationassetclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificationassetclass',
            name='defined_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_allowlist', to='assets.definedmodification'),
        ),
        migrations.AddField(
            model_name='modificationassetclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificationmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificationmodel',
            name='defined_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_allowlist', to='assets.definedmodification'),
        ),
        migrations.AddField(
            model_name='modificationmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='modificationmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatechild',
            name='child_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_child_declarations', to='assets.assetmodel'),
        ),
        migrations.AddField(
            model_name='templatechild',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatechild',
            name='parent_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_declarations', to='assets.configurationtemplate'),
        ),
        migrations.AddField(
            model_name='templatechild',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatemodification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templatemodification',
            name='defined_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_links', to='assets.definedmodification'),
        ),
        migrations.AddField(
            model_name='templatemodification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_links', to='assets.configurationtemplate'),
        ),
        migrations.AddField(
            model_name='templatemodification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assetclassdomain',
            constraint=models.UniqueConstraint(fields=('asset_class', 'domain'), name='uq_asset_class_domain'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['domain'], name='asset_domain__24a786_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_class'], name='asset_asset_c_92c528_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['model'], name='asset_model_i_8c5b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['parent_asset'], name='asset_parent__a26e30_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['root_asset'], name='asset_root_as_22dc46_idx'),
        ),
        migrations.AddIndex(
            model_name='assetparenthistory',
            index=models.Index(fields=['asset', '-created_at'], name='asset_paren_asset_i_2d2f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetclasscapability',
            constraint=models.UniqueConstraint(fields=('asset_class', 'capability_definition'), name='uq_asset_class_capability'),
        ),
        migrations.AddConstraint(
            model_name='assetcapability',
            constraint=models.UniqueConstraint(fields=('asset', 'capability_definition'), name='uq_asset_capability'),
        ),
        migrations.AddIndex(
            model_name='meterhistory',
            index=models.Index(fields=['asset', 'meter_index'], name='meter_histo_asset_i_713a38_idx'),
        ),
        migrations.AddIndex(
            model_name='meterhistory',
            index=models.Index(fields=['recorded_at'], name='meter_histo_recorde_1bec8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelcapability',
            constraint=models.UniqueConstraint(fields=('model', 'capability_definition'), name='uq_asset_model_capability'),
        ),
        migrations.AddConstraint(
            model_name='modeldomain',
            constraint=models.UniqueConstraint(fields=('model', 'domain'), name='uq_asset_model_domain'),
        ),
        migrations.AddConstraint(
            model_name='modelmanufacturer',
            constraint=models.UniqueConstraint(fields=('model', 'manufacturer'), name='uq_asset_model_manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='assetmodel',
            constraint=models.UniqueConstraint(fields=('model_name', 'version'), name='uq_assetmodel_identity'),
        ),
        migrations.AddConstraint(
            model_name='modificationassetclass',
            constraint=models.UniqueConstraint(fields=('defined_modification', 'asset_class'), name='uq_modification_asset_class'),
        ),
        migrations.AddConstraint(
            model_name='modificationmodel',
            constraint=models.UniqueConstraint(fields=('defined_modification', 'model'), name='uq_modification_model'),
        ),
        migrations.AddConstraint(
            model_name='templatemodification',
            constraint=models.UniqueConstraint(fields=('template', 'defined_modification'), name='uq_template_modification'),
        ),
    ]
