# Generated by Django 6.0.7 on 2026-08-15 18:41

import app.events.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('thread_type', models.CharField(choices=[('event', 'Event'), ('photo_gallery', 'Photo Gallery'), ('documentation', 'Documentation')], db_index=True, default='event', max_length=50)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_direct_attachments', models.BooleanField(default=True)),
                ('narrate_file_changes', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('generic', 'Generic'), ('system', 'System'), ('administration', 'Administration'), ('asset_management', 'Asset Management'), ('inventory', 'Inventory'), ('dispatching', 'Dispatching'), ('maintenance', 'Maintenance')], default='generic', max_length=50)),
                ('status', models.CharField(blank=True, choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], max_length=20, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default=None, max_length=20, null=True)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='administration.domain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrationDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'event_detail_administration',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='AssetManagementDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
            ],
            options={
                'db_table': 'event_detail_asset_management',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='DispatchingDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('resource_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'event_detail_dispatching',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='GenericDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
            ],
            options={
                'db_table': 'event_detail_generic',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('item_category', models.CharField(blank=True, max_length=255)),
                ('location_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'event_detail_inventory',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='MaintenanceDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('maintenance_type', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('reactive', 'Reactive'), ('inspection', 'Inspection'), ('preventive', 'Preventive')], max_length=50)),
                ('work_order_reference', models.CharField(blank=True, max_length=100)),
                ('maintenance_schedule', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'event_detail_maintenance',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='SystemDetail',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('affected_component', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
            ],
            options={
                'db_table': 'event_detail_system',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='ActivityThread',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='FileSet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('content', models.TextField()),
                ('is_human_made', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.comment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=app.events.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='events/files/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('is_technical_library', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=app.events.utils.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], default='document', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='events.comment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachment_links', to='events.file')),
            ],
            options={
                'db_table': 'attachment',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('thread_type', 'event')), fields=['status', 'event_start'], name='event_status_start_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='activity_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.activitythread'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.activitythread'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['thread', 'created_at'], name='attachment_thread__74b078_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['comment'], name='attachment_comment_4eb3bf_idx'),
        ),
    ]
