# Generated by Django 6.0.7 on 2026-08-21 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('dispatching', '0001_initial'),
        ('events', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchingdetail',
            name='created_from_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_created', to='dispatching.dispatchtemplaterevision'),
        ),
        migrations.AddField(
            model_name='dispatchingdetail',
            name='previous_dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseding_dispatches', to='events.dispatchingdetail'),
        ),
        migrations.AddField(
            model_name='dispatchingdetail',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchingdetail',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchingdetail',
            name='requested_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches_requested_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_details', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_events_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='maintenance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_details', to='maintenance.maintenanceplan'),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='meter_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='assets.meterhistory'),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='template_action_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_details', to='maintenance.templateactionset'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('thread_type', 'event')), fields=['status', 'event_start'], name='event_status_start_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='activity_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.activitythread'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.activitythread'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['asset'], name='asset_event_asset_i_499273_idx'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['event'], name='asset_event_event_i_e2e04e_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetevent',
            constraint=models.UniqueConstraint(fields=('asset', 'event'), name='uq_asset_event'),
        ),
        migrations.AddConstraint(
            model_name='dispatchingdetail',
            constraint=models.CheckConstraint(condition=models.Q(('desired_start__lte', models.F('desired_end'))), name='dispatch_desired_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='dispatchingdetail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('workflow_status', 'rejected'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='dispatch_rejection_requires_reason'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['thread', 'created_at'], name='attachment_thread__74b078_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['comment'], name='attachment_comment_4eb3bf_idx'),
        ),
    ]
