# Generated by Django 6.0.7 on 2026-08-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('events', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedetail',
            name='maintenance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_details', to='maintenance.maintenanceplan'),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='meter_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='assets.meterhistory'),
        ),
        migrations.AddField(
            model_name='maintenancedetail',
            name='template_action_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_details', to='maintenance.templateactionset'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('thread_type', 'event')), fields=['status', 'event_start'], name='event_status_start_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='activity_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.activitythread'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='events.activitythread'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['thread', 'created_at'], name='attachment_thread__74b078_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['comment'], name='attachment_comment_4eb3bf_idx'),
        ),
    ]
